CREATE TABLE group_mst (
  grp_id INT AUTO_INCREMENT PRIMARY KEY,
  grp_mu_id INT NOT NULL,
  grp_pw TEXT,
  grp_ctg_id INT NOT NULL
);

CREATE TABLE group_dtl (
  grp_dtl_id INT AUTO_INCREMENT PRIMARY KEY,
  grp_id INT NOT NULL,
  title VARCHAR(60) NOT NULL,
  grp_desc TEXT NOT NULL,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE group_user (
  grp_user_id INT AUTO_INCREMENT PRIMARY KEY,
  grp_id INT NOT NULL,
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE group_project (
  grp_prj_id INT AUTO_INCREMENT PRIMARY KEY,
  grp_id INT NOT NULL,
  prj_id INT NOT NULL
);

CREATE TABLE group_task (
  grp_task_id INT AUTO_INCREMENT PRIMARY KEY,
  grp_id INT NOT NULL,
  task_id INT NOT NULL
);

CREATE TABLE group_role_mst (
  grp_role_id INT AUTO_INCREMENT PRIMARY KEY,
  role_lvl INT NOT NULL,
  role_name VARCHAR(10)
);

CREATE TABLE group_category (
  grp_ctg_id INT AUTO_INCREMENT PRIMARY KEY,
  ctg_code INT NOT NULL
);