CREATE TABLE todo_mst (
  todo_id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT NOT NULL,
  su_id INT NOT NULL,
  ru_id INT NOT NULL,
  todo_att_id INT,
  todo_desc TEXT NOT NULL,
  todo_prio INT NOT NULL DEFAULT 1,
  todo_state INT NOT NULL DEFAULT 0,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  cmplt_date TIMESTAMP,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE todo_attachment (
  todo_att_id INT AUTO_INCREMENT PRIMARY KEY,
  todo_id INT NOT NULL,
  attachment TEXT
);